
install:
	test -d seq || virtualenv --system-site-packages seq
	seq/bin/pip install --ignore-installed nltk
	seq/bin/pip install --ignore-installed numpy
	seq/bin/pip install --ignore-installed tqdm
	seq/bin/pip install --ignore-installed matplotlib
